### ISSUE TITLE
Not a valid ERC-20 token ENJ

### ISSUE THREAD

**Issue by tiengthu** [kvhnuke/etherwallet#1091]
Please, help. Yesterday, i bought ENJ token. When the request Gas Limit: 200,000 Gas Price: 60 gwei , but i sent with Gas Limit: 21,000 Gas Price: 35 gwei. And now, my etherwallet shows: Not a valid ERC-20 token ENJ. What can i do now

**Comment by tayvano** [comment]
Are you using the following information?
```
ENJ
Decimals: 18
0xF629cBd94d3791C9250152BD8dfBDF380E2a3B9c
```

**Comment by tiengthu** [comment]
Thank you so much. I have had my token in my wallet.

**Comment by mightyx** [comment]
hm, suddenly I also see in my wallet:

Not a valid ERC-20 token | ENJ

But I should not have this token, or is it related to some other tokens I might have? I was also not able to find it on coinmarketcap.
If I try to add it with your informations above, I get
ERROR: Unable to add a duplicate custom token.

How is it possible to delete/re-add the token? Sorry if noob question.

And could this be some weird advertising hack of ENJ? Since I had no idea about the token..

**Comment by tayvano** [comment]
Fixed
