### ISSUE TITLE
Modal Dialogue 

### ISSUE THREAD

**Issue by asimd** [kvhnuke/etherwallet#1347]
If the user is entering the MEW more than once a day, this really becomes frustrating.

Solutions:
1. Show modal dialogue once per day (first time), expire cookie 24 hours after the initial modal dialogue is shown
2. If it's security measure to show it every single time the user enters MEW, add something like this on screenshot (below the button; at least on every not-first daily visit)
![image](https://user-images.githubusercontent.com/9617780/33485049-362b1876-d6a5-11e7-8e03-f559020e9e43.png)

p.s. just figured clicking anywhere outside the box will exit it, my JS was buggy. But for non-techy people the solutions above wouldn't be bad still

**Comment by tayvano** [comment]
I have it fixed locally. If you think you have it bad, imagine it popping in your face every 2 seconds as you are making small css and copy changes! over and over and over and over and over and over and over and over again. 😊

I'll pull in the outstanding token prs and push live in the next few hours. Sorry for being annoying. The amount of anger and depression and rage and sadness and yelling we are seeing due to loss, especially with price influx, we just wanted to get it up asap.
