### ISSUE TITLE
Clicked on "Sign Message" on the footer and taken to wrong site

### ISSUE THREAD

**Issue by CA2MI** [kvhnuke/etherwallet#1351]
I clicked on Sign Message on the official site and found that it took me to https://harrydenley.com/EtherAddressLookup/phishing.html#https://www.myetherwallet.com/signmsg.html 

I went back and tried it again and got to the correct page, I think.

**Comment by tayvano** [comment]
@CA2MI That certainly looks like the correct URL, but you're the only report that I'm aware of that MEW was blacklisted at any point today (once there was a typo and we blacklisted ourselves. Yes. We smart. 😉)... or that this is happening for anyone else.

It looks like the correct URL to me. Can you triple check your browser history and ensure you were on the right site. Copy and paste the URL here and if it has any hidden characters, it will become obvious.

@409H Did MEW get accidentally blacklisted for any amount of time today?

**Comment by 409H** [comment]
@tayvano not that I can see with GA for `/signmsg.html`.

A while ago Dave Appleton did report that sometimes (when he had like 1000 tabs open) that MyEtherWallet would redirect to the EAL block page. I couldn't reproduce it and it's not been reported since.

![image](https://user-images.githubusercontent.com/2313704/33519948-1e02ff7a-d7a9-11e7-9d36-c92452298e4e.png)
