### ISSUE TITLE
Token Smart Search

### ISSUE THREAD

**Issue by asimd** [kvhnuke/etherwallet#1371]
Let's try making an addition of a custom token less hassle and more user-friendly oriented.

**Story**: As a user, I want to have an option of having a smart search option for adding a token 

**Implementation**: Make parser from Ethplorer to parse responses as shown in pictures below

**Change**: Rename Add Custom Token to Add Token Manually (way less confusion)

I was thinking something like this:
1. Unclicked Button will be added right next to 2 existing ones
![image](https://user-images.githubusercontent.com/9617780/33656760-55048810-da77-11e7-8106-fe28477cfcc8.png)
2. If the **Token Smart Search** button is clicked, show the input search field 
![image](https://user-images.githubusercontent.com/9617780/33657195-c8df3bf8-da78-11e7-9833-74c2d1da488d.png)
3. When the value is entered and the token is "searched for", the responses are shown as in the SS. Simple click to add token.
![image](https://user-images.githubusercontent.com/9617780/33656840-a86e9644-da77-11e7-98fb-36c29130263d.png)
4. If their API is down, just show "Ethplorer.io API is down. Please try again later or try **adding a token manually**"

p.s. I don't think folks from Ethplorer would mind gaining some popularity :)

**Comment by tayvano** [comment]
Due to the fragility of this hot-mess codebase, we aren't touching tokens. We know it sucks but the last time we had to fix a bug that could potentially cause loss it was a huge undertaking.

You can see the new implementation here: https://github.com/MyEtherWallet/MyEtherWallet/pull/538

And provide any feedback here: https://github.com/MyEtherWallet/MyEtherWallet/issues/494
