### ISSUE TITLE
Versions 3.11.1.2,3,4 are broken while 3.11.1.1 is OK

### ISSUE THREAD

**Issue by Zloy** [kvhnuke/etherwallet#1449]
See here https://pasteboard.co/H0aq8eP.png

---
Windows 8.1 64 bit, Chrome 62.0.3202.94

**Comment by cidlc** [comment]
Well, not really. Download the zip from here instead: https://github.com/kvhnuke/etherwallet

**Comment by tayvano** [comment]
What good is Travis if it can't even zip a file? 

Ill manually do them I guess.

**Comment by Zloy** [comment]
Really, I've just double checked it from here https://github.com/kvhnuke/etherwallet/releases/download/v3.11.1.4/etherwallet-v3.11.1.4.zip
Still fails. What *exact* URL shall I try next?

**Comment by cidlc** [comment]
https://github.com/kvhnuke/etherwallet/archive/mercury.zip This is what you have to download. Once you do it, extract, go to the dist folder and open index.html.

**Comment by cidlc** [comment]
@kvhnuke has to fix the link he provided in the guide.

**Comment by Lendoit** [comment]
Same problem. Version etherwallet-v3.11.1.4 is not running locally.

Log:

etherwallet-master.js:97820 Uncaught ReferenceError: baseUrls is not defined
    at etherwallet-master.js:97820
    at Object.<anonymous> (etherwallet-master.js:97981)
    at Object.272 (etherwallet-master.js:97985)
    at s (etherwallet-master.js:1)
    at etherwallet-master.js:1
    at Object.86.marked (etherwallet-master.js:10148)
    at s (etherwallet-master.js:1)
    at etherwallet-master.js:1
    at Object.59../ajaxReq (etherwallet-master.js:7048)
    at s (etherwallet-master.js:1)
(anonymous) @ etherwallet-master.js:97820
(anonymous) @ etherwallet-master.js:97981
272 @ etherwallet-master.js:97985
s @ etherwallet-master.js:1
(anonymous) @ etherwallet-master.js:1
86.marked @ etherwallet-master.js:10148
s @ etherwallet-master.js:1
(anonymous) @ etherwallet-master.js:1
59../ajaxReq @ etherwallet-master.js:7048
s @ etherwallet-master.js:1
e @ etherwallet-master.js:1
(anonymous) @ etherwallet-master.js:1
etherwallet-master.js:27535 Uncaught Error: [$injector:modulerr] Failed to instantiate module mewApp due to:
Error: [$injector:nomod] Module 'mewApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.6.8/$injector/nomod?p0=mewApp
    at file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:27535:14
    at file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:29673:19
    at ensure (file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:29594:40)
    at module (file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:29671:16)
    at file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:32346:24
    at forEach (file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:27827:22)
    at loadModules (file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:32330:7)
    at createInjector (file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:32240:21)
    at doBootstrap (file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:29329:22)
    at bootstrap (file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:29348:14)
http://errors.angularjs.org/1.6.8/$injector/modulerr?p0=mewApp&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'mewApp'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.8%2F%24injector%2Fnomod%3Fp0%3DmewApp%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FDev%2FRep%2Fetherwallet-v3.11.1.4%2Fjs%2Fetherwallet-master.js%3A27535%3A14%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FDev%2FRep%2Fetherwallet-v3.11.1.4%2Fjs%2Fetherwallet-master.js%3A29673%3A19%0A%20%20%20%20at%20ensure%20(file%3A%2F%2F%2FC%3A%2FDev%2FRep%2Fetherwallet-v3.11.1.4%2Fjs%2Fetherwallet-master.js%3A29594%3A40)%0A%20%20%20%20at%20module%20(file%3A%2F%2F%2FC%3A%2FDev%2FRep%2Fetherwallet-v3.11.1.4%2Fjs%2Fetherwallet-master.js%3A29671%3A16)%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FDev%2FRep%2Fetherwallet-v3.11.1.4%2Fjs%2Fetherwallet-master.js%3A32346%3A24%0A%20%20%20%20at%20forEach%20(file%3A%2F%2F%2FC%3A%2FDev%2FRep%2Fetherwallet-v3.11.1.4%2Fjs%2Fetherwallet-master.js%3A27827%3A22)%0A%20%20%20%20at%20loadModules%20(file%3A%2F%2F%2FC%3A%2FDev%2FRep%2Fetherwallet-v3.11.1.4%2Fjs%2Fetherwallet-master.js%3A32330%3A7)%0A%20%20%20%20at%20createInjector%20(file%3A%2F%2F%2FC%3A%2FDev%2FRep%2Fetherwallet-v3.11.1.4%2Fjs%2Fetherwallet-master.js%3A32240%3A21)%0A%20%20%20%20at%20doBootstrap%20(file%3A%2F%2F%2FC%3A%2FDev%2FRep%2Fetherwallet-v3.11.1.4%2Fjs%2Fetherwallet-master.js%3A29329%3A22)%0A%20%20%20%20at%20bootstrap%20(file%3A%2F%2F%2FC%3A%2FDev%2FRep%2Fetherwallet-v3.11.1.4%2Fjs%2Fetherwallet-master.js%3A29348%3A14)
    at file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:27535:14
    at file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:29673:19
    at ensure (file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:29594:40)
    at module (file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:29671:16)
    at file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:32346:24
    at forEach (file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:27827:22)
    at loadModules (file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:32330:7)
    at createInjector (file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:32240:21)
    at doBootstrap (file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:29329:22)
    at bootstrap (file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:29348:14)
http://errors.angularjs.org/1.6.8/$injector/modulerr?p0=mewApp&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'mewApp'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.8%2F%24injector%2Fnomod%3Fp0%3DmewApp%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FDev%2FRep%2Fetherwallet-v3.11.1.4%2Fjs%2Fetherwallet-master.js%3A27535%3A14%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FDev%2FRep%2Fetherwallet-v3.11.1.4%2Fjs%2Fetherwallet-master.js%3A29673%3A19%0A%20%20%20%20at%20ensure%20(file%3A%2F%2F%2FC%3A%2FDev%2FRep%2Fetherwallet-v3.11.1.4%2Fjs%2Fetherwallet-master.js%3A29594%3A40)%0A%20%20%20%20at%20module%20(file%3A%2F%2F%2FC%3A%2FDev%2FRep%2Fetherwallet-v3.11.1.4%2Fjs%2Fetherwallet-master.js%3A29671%3A16)%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FDev%2FRep%2Fetherwallet-v3.11.1.4%2Fjs%2Fetherwallet-master.js%3A32346%3A24%0A%20%20%20%20at%20forEach%20(file%3A%2F%2F%2FC%3A%2FDev%2FRep%2Fetherwallet-v3.11.1.4%2Fjs%2Fetherwallet-master.js%3A27827%3A22)%0A%20%20%20%20at%20loadModules%20(file%3A%2F%2F%2FC%3A%2FDev%2FRep%2Fetherwallet-v3.11.1.4%2Fjs%2Fetherwallet-master.js%3A32330%3A7)%0A%20%20%20%20at%20createInjector%20(file%3A%2F%2F%2FC%3A%2FDev%2FRep%2Fetherwallet-v3.11.1.4%2Fjs%2Fetherwallet-master.js%3A32240%3A21)%0A%20%20%20%20at%20doBootstrap%20(file%3A%2F%2F%2FC%3A%2FDev%2FRep%2Fetherwallet-v3.11.1.4%2Fjs%2Fetherwallet-master.js%3A29329%3A22)%0A%20%20%20%20at%20bootstrap%20(file%3A%2F%2F%2FC%3A%2FDev%2FRep%2Fetherwallet-v3.11.1.4%2Fjs%2Fetherwallet-master.js%3A29348%3A14)
    at file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:27535:14
    at file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:32370:17
    at forEach (file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:27827:22)
    at loadModules (file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:32330:7)
    at createInjector (file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:32240:21)
    at doBootstrap (file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:29329:22)
    at bootstrap (file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:29348:14)
    at angularInit (file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:29238:7)
    at file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:61034:5
    at HTMLDocument.trigger (file:///C:/Dev/Rep/etherwallet-v3.11.1.4/js/etherwallet-master.js:30836:7)
(anonymous) @ etherwallet-master.js:27535
(anonymous) @ etherwallet-master.js:32370
forEach @ etherwallet-master.js:27827
loadModules @ etherwallet-master.js:32330
createInjector @ etherwallet-master.js:32240
doBootstrap @ etherwallet-master.js:29329
bootstrap @ etherwallet-master.js:29348
angularInit @ etherwallet-master.js:29238
(anonymous) @ etherwallet-master.js:61034
trigger @ etherwallet-master.js:30836

**Comment by Lendoit** [comment]
![image](https://user-images.githubusercontent.com/32183210/34389696-e1a868f4-eb43-11e7-85fa-1eb6e20eec0d.png)

**Comment by cidlc** [comment]
You opened it through the broken zipfile @Lendoit

**Comment by tayvano** [comment]
Just manually updated all of these. The originals are now labeled -broken.zip but remain in case we ever need to reference them. I will also be pushing a new version in a couple hours. 

Please let me know if you are still having issues.

A note for PC users: I have no idea what I'm talking about but you are going to want to **extract** the zip file to a separate location and then open index.html. For some reason, people sometimes open them within the zip file and it doesnt work good or something?

**Comment by tayvano** [comment]
e.g https://github.com/kvhnuke/etherwallet/releases/tag/v3.11.1.4

**Comment by repsorp** [comment]
v3.11.1.4 working fine for me now
thanks

**Comment by Lendoit** [comment]
Yes, the new v3.11.1.4 is working Ok.
But the latest v3.11.1.5 is broken now.

**Comment by repsorp** [comment]
Confirmation v3.11.1.5 is broken

**Comment by tayvano** [comment]
So the automated builds are still broken. ☹. 

Just updated v...5 to be the manual zip from my computer. Looking into why this could be

**Comment by Zloy** [comment]
Versions 3.11.1.5, 6 work now.

**Comment by repsorp** [comment]
v3.11.1.7 is broken

**Comment by tayvano** [comment]
fixed.

fucking travis. anyone have any ideas?

**Comment by repsorp** [comment]
sorry no idea...
may be something here:
https://docs.travis-ci.com/user/common-build-problems/

**Comment by gamalielhere** [comment]
@repsorp can you confirm if the newer zips are working correctly on your end?

**Comment by repsorp** [comment]
v3.21.03 is ok for me
zip correctly working

**Comment by gamalielhere** [comment]
Sounds good. Closing this for now. Don't hesitate to reopen this if anything.
