### ISSUE TITLE
Tokens disappearing

### ISSUE THREAD

**Issue by ugilio** [kvhnuke/etherwallet#171]
With latest version on mercury branch, if you go to "Send tokens":
- Between "Amount to send" and "Gas" there is the list of tokens where you can select the token you want to send
- On the sidebar there is Token Balances, showing the "loading" placeholder for all the tokens

As soon as the "loading" placeholder disappears for a token, the corresponding token is removed from the "selectable list"! So you gradually see DAO disappearing and appearing in the sidebar, then DGD, then DGDb... in the end only "Custom" remains

I see this with both Firefox and Chrome

**Comment by tayvano** [comment]
I'm experimenting with hiding tokens from underneath the "amount" field if the amount is 0. However, I don't think the execution is great right now.

Over the next month or so we are going to be adding Augur and DGX and who knows what else to this list. I don't have a problem with them in the sidebar, but it gets super cluttered under the amount.

I may switch it to show if !== 0 instead of hide == 0, so you don't see them appearing / disappearing. Again, not sure about the execution at this point though.

**Comment by ugilio** [comment]
Ah ok, I was experimenting with a newly created private key so obviously all tokens and balance was zero. I did not know it was a feature, but now that you tell me it makes sense.
