### ISSUE TITLE
Uppercase hex letters in ETH address fail on Offline Send Step 1

### ISSUE THREAD

**Issue by l8nite** [kvhnuke/etherwallet#1924]
Trying to use this: https://www.myetherwallet.com/#offline-transaction

Input "From Address" for Step 1: Generate Information (Online Computer):

The address I used is: 0xAA7f9d16df7eb2ec96ca6318b0129423730a87ac 

Expected: It generates the gas price and nonce.
Actual: It fails to recognize the address and doesn't do anything.

If I change the address to use lower-case "aa" at the beginning, it works as expected.

![image](https://user-images.githubusercontent.com/1711530/41870661-78c00b42-7871-11e8-9641-a74f8849c22d.png)

![image](https://user-images.githubusercontent.com/1711530/41870669-833aa9c4-7871-11e8-8c04-553f2b1f8f6d.png)

**Comment by wbobeirne** [comment]
@l8nite capitalization in addresses is what's known as "checksumming". This makes it really difficult to trick someone with a fake address that's one character different, since the capitalization would be entirely different, even though there's only 1 character changed.

However, not all apps show checksummed addresses, so addresses only work in one of three cases:

* The address is ALL lowercase
* The address is ALL uppercase
* The address has the correct checksum

When you make the first two characters AA, you are no longer all lower or upper, so it makes sure you have the correct checksum. The *actual* correct checksum for your address is `0xAA7F9D16df7EB2ec96Ca6318B0129423730a87Ac`. If you enter that, it should work fine.

Hope this helps!

**Comment by l8nite** [comment]
Thank you!
