### ISSUE TITLE
Watch-Only Address

### ISSUE THREAD

**Issue by hawks5999** [kvhnuke/etherwallet#22]
Possible to add a watch-only address with public key but no private key stored?

**Comment by tayvano** [comment]
I don't hate this and I especially love it for the Chrome Extension. However, perhaps on a new tab or make it so stupidly explicit they they are just viewing a wallet.

I'm becoming jaded because I've literally spent 6 hours today helping people (PLEASE DO NOT CALL MY CELL PHONE!!!!! Also, I have a real job!) who have "lost" a key piece of information that they need to access their wallet. I say "lost" because they didn't even know they needed it! They thought they had access because they saw their balance on etherchain. I hate to design for the lowest common denominator but seeing people "lose" thousands of ETH in this way is so freaking painful.

Anyone else feel free to chime in. We should be pushing an update ~Monday and _may_ include this.

**Comment by hawks5999** [comment]
New Tab sounds viable. Maybe titled something like "Expert Settings" or
"Advanced Configuration" or some other scary sounding technical term with
all sorts of BIG RED WARNING words all across the top of it.

**Comment by tayvano** [comment]
@hawks5999 - This was implemented and pushed a couple days ago! Thanks for the suggestion. I do really like it.

**Comment by hawks5999** [comment]
Thanks! It works great in the full page view. 
I got it setup and working with an address. 
Two bits of feedback.
1) As a nice-to-have feature, parsing and accepting addresses without the leading 0x.... might be helpful to others. For example, I have a json file with presale wallet and the address is expressed without the leading 0x (snip: "ethaddr": "2a59e4...."). I received invalid address errors a couple times trying to add the address before realizing my mistake. Yep, even with the help text in the address field. Assuming the universe keeps making bigger idiots like myself, this small bit of idiot-proofing might be a plus.
2) The watch address doesn't show in the popup view from the extension button in the browser bar. 
![image](https://cloud.githubusercontent.com/assets/922019/13586572/9cbba1e6-e476-11e5-9b0f-b44244018566.png)
Thanks!
