### ISSUE TITLE
Unexpected token U in JSON at position 0

### ISSUE THREAD

**Issue by apobekiaris** [kvhnuke/etherwallet#239]
When ever i try to initiate a transaction from the chrome addin I get this error, it looks like it is before validating the wallet password

**Comment by tayvano** [comment]
I believe this happens when your JSON file has been saved as a rich text document. Did you re-save your JSON file at any point?

Open it in notepad or textedit or a text editor like sublime text and take a look. It should look like:

`{"version":3,"id":"de466439-e8c1-42f9-af21-f9f72af30042","address":"488a6bbea3ebd94125c8cc535d8e1f690799812c","Crypto":{"ciphertext":"7e4fa7338ded25cc818b0c8222c4e105eca27424bf6e9a410f4e4319ceae5c55","cipherparams":{"iv":"42dbbdb5d2cfaf524c7fee75e093fa09"},"cipher":"aes-128-ctr","kdf":"scrypt","kdfparams":{"dklen":32,"salt":"1c6e9fc3265e942d40ad549cb2faf78416bad8413e7fd05eef918652c379cfd5","n":1024,"r":8,"p":1},"mac":"eb0bff33cbca14e04603a9980442cf519b4214b3347ad71372b0fdb5c3ed648c"}}`

or something similar. If there are a lot of extra stuff in it and its starts with UTF-8, that would be your problem.

Try saving it as a .txt file using those programs and seeing if that removes the additional code. 

There are also some other troubleshooting methods we can do.

Do you have any other copy or version of that wallet? Paper? Raw private key?

**Comment by apobekiaris** [comment]
On Tue, Oct 11, 2016 at 11:58 PM, Taylor Van Orden <notifications@github.com

> wrote:
> 
> I believe this happens when your JSON file has been saved as a rich text
> document. Did you re-save your JSON file at any point?

I am not sure how this answer relates to my question, what I use is the
chrome extension and the wallet is already displayed there. I did open a
back I had and the format looks like what you said but starts form the
address however this is a backup on my disk and not the chrome extension
wallet

## 

Apostolis Bekiaris
Frameworks Technical Evangelist @ DevExpress
Blog @ http://apobekiaris.blogspot.com
Skype/twitter: tolisss

**Comment by apobekiaris** [comment]
hmm apparently there is an issue with the chrome extension since after my
today attempt to use it i got a corrupted extension message. So more
problems coming :(

1) do I need to make wallet back on every transaction I make?
2) I tried the chrome extension to add wallet so I click on Add wallet then
I click Select Your Wallet File (Keystore / JSON) then point to my walett
backup then password then unlock but there is no way to persist that wallet
in the extension somehow

[image: Inline image 1]

On Mon, Oct 17, 2016 at 12:44 PM, Apostolis Bekiaris <
apostolis.bekiaris@gmail.com> wrote:

> On Tue, Oct 11, 2016 at 11:58 PM, Taylor Van Orden <
> notifications@github.com> wrote:
> 
> > I believe this happens when your JSON file has been saved as a rich text
> > document. Did you re-save your JSON file at any point?
> 
> I am not sure how this answer relates to my question, what I use is the
> chrome extension and the wallet is already displayed there. I did open a
> back I had and the format looks like what you said but starts form the
> address however this is a backup on my disk and not the chrome extension
> wallet
> 
> ## 
> 
> Apostolis Bekiaris
> Frameworks Technical Evangelist @ DevExpress
> Blog @ http://apobekiaris.blogspot.com
> Skype/twitter: tolisss

## 

Apostolis Bekiaris
Frameworks Technical Evangelist @ DevExpress
Blog @ http://apobekiaris.blogspot.com
Skype/twitter: tolisss

**Comment by apobekiaris** [comment]
anyone?

**Comment by apobekiaris** [comment]
up2u my reviews will burn u and with all rights your support is zero and the wallet not stable

**Comment by j13n** [comment]
Actually, I have the same problem as well.

**Comment by apobekiaris** [comment]
if u lucky u do not have enough money in that wallet cause it seems that these a scum which apparently forget that we also have power in our hands and we can create bad publicity for them. ALready posted a few reviews and i suggest u do the same maybe this will wake them up

**Comment by tayvano** [comment]
Wow. @apobekiaris - we provide a free, open source service in which we remind you numerous times to BACK UP YOUR PRIVATE KEYS IN NUMEROUS LOCATIONS. I have been terrifically busy the past couple weeks so I apologize for not getting to your questions but you have no right to speak to me in this way, nor do you have the right to "post numerous reviews" shitting on our service. 

Let me remind you, once again: MyEtherWallet.com & MyEtherWallet CX are not "web wallets". You do not create an account or give us your Ether to hold onto. All data never leaves your computer/your browser. We make it easy for you to create, save, and access your information and interact with the blockchain.

> 1) do I need to make wallet back on every transaction I make?

No. 

> 2) I tried the chrome extension to add wallet so I click on Add wallet then I click Select Your Wallet File (Keystore / JSON) then point to my walett backup then password then unlock but there is no way to persist that wallet in the extension somehow

In order to add the wallet to the Chrome Extension you must first remove the existing wallet:
1. Make a backup of your private key or keystore file from your Chrome Extension.
2. Go to Send Ether on MyEtherWallet.com and make sure you can access your wallet via there.
3. If and only if you are able to access your wallet on MyEtherWallet.com, remove the wallet from the Chrome Extension and then re-add it using the keystore file you saved. 

I hope this solves you problem but I am not going to be helping you any further due to your incoherent & rude messages. Best of luck to you.

**Comment by kvhnuke** [comment]
Please feel free to use your power, we do everything we can and fix bugs as we get time to work on them. We also have day jobs which allow us to offer these services for free to you and pay for the servers which you are using. Ill look into this at my earliest convenience but I don't appreciate the way how you are handling this issue.

**Comment by apobekiaris** [comment]
@tayvano  nice I see you wake up and left your mirror and your make ups. Now can you please focus on my question? What I ask is really simple and u keep lock my money for so long. Where is the button to add the wallet? Am I not clear? **I can add the wallet unlock it but does not persist**

**Comment by tayvano** [comment]
Haha. I guess I wasn't clear: we don't provide support to dicks such as yourself. We are not a web wallet and do not have your funds, nor do we have the ability to lock up said funds. 

Have a nice evening.

**Comment by apobekiaris** [comment]
@tayvano 

yeah its obvious u do not know what your project or os in general is about maybe u should ask your dolls

**Comment by apobekiaris** [comment]
@tayvano btw i am sure u learn your lesson by now and at least u will provide better support to others from now on. and btw my wallet is empty cause i would never trust my money to a project which prioritize mirrors makeups and dolls. Same nice evening to you :)

**Comment by kvhnuke** [comment]
Seriously dude go take a chill pill, the only reason why your issue is going down in the list is cz of your rude personality. No shit your funds are locked up!

**Comment by apobekiaris** [comment]
yeah try twice to lock them up hahahhahahah u dump head people

**Comment by kvhnuke** [comment]
Hahahahahahahaha so funny we have a comedian in the house 😂

**Comment by tayvano** [comment]
@apobekiaris I literally answer 50+ emails per day helping people. I am NOTHING but kind and patient until people like you act like misogynistic dweebs who cannot read, nor write. I took 7 days off to get married. Instead of allowing me to help you by....you know....reading what I had posted 15 days ago (exactly 1 day after you initially asked your question) you decided I wasn't helping you. 

You have never once answered any of the troubleshooting questions I asked. Instead you resort to personal attacks. 

You are not my client. You are not my boss. You are not even my customer. You are a user. That is it. 

You are using a free, open source service that we have built, maintained, and supported for over a year now. We do everything we can to help people but, since you are not our customer, we have no problem NOT wasting our time on people like you. Instead we will help the folks who can read, write, answer questions, and provide the necessary details. Please, don't use our service any longer as we will NOT support you.
