### ISSUE TITLE
Restore MyEtherWallet and have a shortcut access to the desktop

### ISSUE THREAD

**Issue by TonyMarq** [kvhnuke/etherwallet#288]
Hi,

Can someone help me restore MyEther Wallet?
Also, how do I create a Desktop icon to access it.?

Thanks,
Tony

**Comment by tayvano** [comment]
> Can someone help me restore MyEther Wallet?

Can you please explain what you mean by this?

> Also, how do I create a Desktop icon to access it.?

http://www.laptopmag.com/articles/how-to-create-desktop-shortcuts-for-web-pages-using-chrome

**Comment by TonyMarq** [comment]
Hi, and thank you for the response. I'm trying to get a visual wallet icon of My Ether Wallet that similar to any other offline wallet like Jaxx, Exodus, that show up as an icon on my desktop. For some reason, I thought I could do this. Or, is etherscan.io the only way to view the account?

**Comment by tayvano** [comment]
Ah. I'm guessing you can manually change the icon yourself since we're a website it's probably going to be the Chrome icon by default. Here's the logo. 

![etherwallet-logo-02 copy](https://cloud.githubusercontent.com/assets/7924827/20503396/2fe802ba-aff7-11e6-9780-278ae126ae63.png)

Etherscan is quickest way to view transaction history and current balance. You can also do so on the  https://www.myetherwallet.com/#view-wallet-info page or download the chrome extension [here](https://chrome.google.com/webstore/detail/myetherwallet-cx/nlbmnnijcnlegkjjpcfjclmcfggfefdm) and you can add your wallet and have quick access to your balances in chrome.
