### ISSUE TITLE
Please, add the possibility to use Google Authenticator and/or Yubikey 2FA to secure transactions

### ISSUE THREAD

**Issue by Nogreedy** [kvhnuke/etherwallet#292]
Please, add the possibility to use Google Authenticator and/or Yubikey 2FA to secure transactions
Thanks for your great app - website.

**Comment by Nogreedy** [comment]
@tayvano 
Is it possible to add a label or comment please?
Thanks.

**Comment by Nogreedy** [comment]
@kvhnuke @tayvano
Is it possible for you to add a label or comment this issue please?
Thanks.
Happy new year.

**Comment by tayvano** [comment]
As we have no servers, there is no way to add Google Authenticator or other 2FA providers. 

The entire point of 2FA is to require a server to not give access unless 3 pieces of information are given: username, password, correct answer to 2fa challenge. 

This is NOT how MyEtherWallet nor Ethereum works. 

MyEtherWallet allows YOU via YOUR BROWSER to sign transactions with your private key and broadcast them to the network. The Ethereum network - the blockchain itself - takes the address associated with this transaction and "moves" the ETH from that address to the address you specify in the transaction. There are no servers involved.

The password only comes into play when decrypting an encrypted private key. Again, this password is not going to a server somewhere or the blockchain or anything. Your browser attempts to decrypt the file you give it with the password you also give it. If it works, it works and you have a private key and you can sign a transaction. If it doesn't, it assumes the password is wrong, and you don't have a key. 

In order to activate 2FA, we would have to store your key on our servers. Even with 2FA, this is far LESS secure (not to mention, far more centralized) than our current method of never saving, storing, or transmitting your private key ever.

**Comment by Nogreedy** [comment]
@tayvano @kvhnuke 
Thanks for your answer.
For your information, Electrum wallet (for Bitcoin of course) uses 2FA with multiSig
It uses an external service (TrustedCoin -  paid service - costs 0.0005 BTC/transaction) and Google Authenticator
Bitcoins are stored at a 2-of-3 multisig address.
I know it's different way from how MyEtherWallet works but with MyEtherWallet, if you don't use Ledger Nanao S and if a computer is compromised with malware, an attacker would then be able to steal coins. 
http://docs.electrum.org/en/latest/2fa.html
https://api.trustedcoin.com/#/electrum-help

**Comment by tayvano** [comment]
> Bitcoins are stored at a 2-of-3 multisig address.

And this is a very key difference. In this case, one of your private keys is stored on a server. You can only not have your keys compromised if you **don't** keep both keys on your computer. While this is great in theory, in reality using an online service to provide you with 2 keys means that both keys are on your internet-connected device at some point. So if the site is compromised at any point & your 2 keys are compromised upon generation, you're still fucked. And if you store both keys on your computer and your computer is compromised, you're still fucked. And if the server is compromised and one of your keys is compromised, again, you're fucked.

Ether.li attempted to do 2-of-3 multisigs and there are a number of problems today:

1. Since they are a contract address, they require more gas to be sent with any transaction to that address, which a lot of exchanges still somehow haven't figure out how to do. They send with 21000 gas, the transaction fails, and people are confused.

2. Even though its 2 of 3 so technically users should be able to get their funds out if that service disappears, people somehow don't get that. See numerous posts about people confused about how to access their ether.li funds.

3. There are far less options for multisig right now than non-multisig. In fact, the only one is Mist. 

4. It costs money to start a multisig in Ethereum (for gas). Based on the 10+ emails/day from people who don't have any ETH and can't send tokens / withdraw from The DAO, it's not feasible to expect most people to be able to pay upfront to start this wallet.

Perhaps in the future when external services figure out how to estimate gas and the multisig and user ecosystem is more evolved, we will reconsider. At this point, there are about 10000 other things on our to-do list and this just isn't one of them. We have no interest in holding any keys or dealing with the myriad of security and support issues that come with it. 

Even then, I would still recommend that an offline paper wallet + offline transactions or an dedicated device (Ledger) is going to be your safest & most decentralized option.

**Comment by Nogreedy** [comment]
@tayvano Thanks so much for your detailed and intelligent answer.

**Comment by GILLIARDFN** [comment]
TIVE 4 MIL US ROUBADO HOJE ESTA CARTEIRA É UMA PORCARIA

**Comment by fty48jj19** [comment]
e   sem uma chave fica dificio tem que ter porque se nao fica mas façio para o rakes veja  as pessoa tem q se conecneta porque falo isso aconpanha  minha visao de segurança  vc tem seu celular vc vai ter seja uma chave no seu celular mas nao e no aplicativo nao e  no aplicativo mas nao conecta nada de aplicativo nao  eziste uma configuraçao acredito que muito sabe fazer essa configuraçoes  se nao sabe e pedir alguem para resetar  o aparelho para nao colher virus entra com uma entrada nova configuraçoes com a enternet  sino celular nao no aplicativo nao hoje esta muito dificio vc cocnetar aplicativo com feus fudo e facio  d qualquer um roubar  aquino brasil  conta digitala a cartao que os raque faz  ele pega numero do cartao  seu numero cpf  senha  com ajuda de aguem q trabalha no banco senha  eletronica cpnj   sai da onde vc pode produzir nao clonagem e feito por quem clonagem gente e um cartao vigem ta eles pega seu nome seu numero de documento seu nome completo no do banco agencia tudo etc..  aqui no brasil  e asim que os raques fazem eles entra no aplicativo mas poque isso as pessoas estao acustumado fazer suas seguraças de fundos com aplicativos muito aplicativos sao o alvo dos rakes nao se deve dexar nada se deve si anota numero de servidor nao pegar anota seus fudos tudo nao fazer configuraçoes com a enternet  ter uma senha diferente ,

**Comment by fty48jj19** [comment]
e  gente eu hoje que trazer fazer uma colocaçao para todos o aponzetado aqui no brasil esta sendo roubado porque a uma faceta facio no celular aplicativos com virus quando vc meciona a ja alguem para colher seus dados  e  poque isso o facebook ja tida o quer seu numero tel ,

**Comment by fty48jj19** [comment]
vcs querem saber da verdade  celular a muitas coisa que pode ser descoberto vc adciona um aplicativo ali vc tem sabe o que vai fazer documentos nao se pode guarda nem senha nada que seja enportante porque o golpista o alvo dele e celular  tem um codigo para quem nao sabe ele pesca seu numero da receita federal  tenha muito cuidados com documents enportantes  orgao pesoas..

**Comment by fty48jj19** [comment]
ou pessoas q trabalha para o governo tem sempre alguem la que sabe seu numero de cpf  e nisso nos araquivos a o codigo os golpista usa muito isso e com enprantaçao da chave em verificaçao de 2 etapa e fica difiçio alguem clona que e seu primeira coisa que vai procura e no celular algumas pessoa nao sabe usar um celular ai guarda tudo em aplicativo olha o perigo   na enternet vc tem que costrui ...

**Comment by fty48jj19** [comment]
contrui uma senha bem forte pela entenet no banco aciona 24 horas  senha de segurança porque 2 senha poque na dgital se o golpista descubri ele nao vai ter asseso ala banco n 24 horas  digo isso porque ja aconteceu isso comigo ele descubrirao senha minha mas banco broquiou  ele tentou entra na conta seja tentou adivinha a aoutra senha fui no banco eu sendo o dono da conta desbroquiei,

**Comment by fty48jj19** [comment]
i  que estou falando serve para todos que tem conta  ta  no banco muito usa chip caixa para crona sua senha mas no 24 e dificio eles achar  muito sabe disso mas tem pessoas que nao sabe disso que estou falando ter cuidado com parentes e amigos  as ves aconteçe coisas vc fica em duvida procure olhar bem que esta fazendo nas aplicaçoes bom gente e isso ,

**Comment by fty48jj19** [comment]
e  eu esquiçi  de explica como fuciona muito simples  vc adiciona google  com seu mail  e  altomaticamente o google vai pdir seu numero para endentifica vc  que o celular e rastreado seu nome numero atraves deses esquema  vc sera dona da sua conta se tiver tudo certinho agora se vc tiver com celular de alguem seu mail nao vai fuciona nao de jeito neum,

**Comment by fty48jj19** [comment]
e    mas isso vc adiciona no seu smt fone  pedino configuraçoes de 2 etapa
muito facio   vc escreve seu mail quando vc abre o google  ele pde o a
senha  mas nessa etapa e diferente  vc vai coloca seu mail  e o google vai
pedir senha do seu smat fone se for vc o dono  esta tudo certo agora se vc
tiver usando um celular mesmo que sja  empretado conta sua nao vai responde
nao ,

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em qua, 13 de mar de 2019 às 20:53, joao tv <notifications@github.com>
escreveu:

**Comment by fty48jj19** [comment]
yes also have in the avast  key also l forgot  to even explain it to you,

**Comment by fty48jj19** [comment]
vc tera varia opeçao  uma enpotese q vc perde seu celular   vc teno uma senha banco diferente se aguem rouba seu celular  ele vai pensar  que vai pode chega no caixa para fazer retirada nao porque o banco reconheçe vc  quando ele acionar o banco vai logo pedir outra asenha ele nao vai saber  nao ai pode fazer nada o magnetico do banco sabe que e vc  vc pode emitir 24 hora outra senha diferente

**Comment by fty48jj19** [comment]
maoria dos bancos tem o 24 horas  e igual carro quandom ladrao rouba o magnetico so reconheçe o dono se outra pessoa tenta roubar  o alarme despara e a sentral aciona logo policia mesma coisa celular vc tem sua senha no banco vc faze outra diferente eu nao sei se seu pais fuciona asim aqui no brasil fuciona asim ,

**Comment by fty48jj19** [comment]
cateira  nao deixar senha  chave tira da entenet gurda num papel  se vc joga senha nao faz privado  os golpista acha e rouba  tudo que vc tem quando vc fizer um carteira copia pega uma caneta escrve sua senha  e guarda fora do celular  ou entenet ou vc zip com senha bem forte uma senha so vc saiba ,

**Comment by fty48jj19** [comment]
esa sua senha e pubrica  pode usar  so nao a chave da sua conta  que vc tem
fazer  pedir o banco 24 horas  permisao para vc usar outra senha diferente
iso nao e comigo nao so estou explicando que tem ser feito   so isso,

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em qua, 13 de mar de 2019 às 21:36, joao tv <notifications@github.com>
escreveu:

**Comment by fty48jj19** [comment]
mas isso ja falei isso nao e feito asim nao e no banco  e nao senha de
moedas nao estou falando de  fudos money  banco que vc tem dpositado algo

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em qua, 13 de mar de 2019 às 21:40, joao tv <notifications@github.com>
escreveu:

**Comment by fty48jj19** [comment]
e  como ja falei  carteira tem saber usar  tem uma carteira ela e muito visada pelo golpista [   https:www.myethewallet.com   essa carteira  se vc vacilar nela  os golpista decobre sua senha  como quando vc  adiciona a carteira seja qualquer uma  veha se o seu saite e verdadeiro  mas como  vc olha uma estrelas q tem no canto da sua enternet  veja se estrela  e azul  os golpita lança saite igual tambem  a uma verdadeira ou seja ele emite saite falço,
