### ISSUE TITLE
Allow selection of BIP 44 accounts (BIP 44 level 3 index)

### ISSUE THREAD

**Issue by mmazi** [kvhnuke/etherwallet#307]
MyEtherWallet seems to only ever use the `m/44'/60'/0'/0/0` [BIP 44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) path. As a user, I'd like to be able to select the _account_ number, i.e. the 3rd level index in the chain that is now fixed to `0'`.

(The fourth level (_change_) probably doesn't need to be selectable by the user as it is a technical detail, and moreover only makes sense in the context of Bitcoin and other UTXO-based coins, and not Ethereum. The fifth level is already selectable (sequentially) by the user.)

**Comment by mmazi** [comment]
Um, actually it seems that MyEtherWallet uses `m/44'/60'/0'` (with Ledger Wallet) and derives addresses directly from this key as children instead of deriving keys from its 0-indexed child (the external chain) as specified by BIP 44. Why is this so?

**Comment by tayvano** [comment]
We use the specifications and paths used by metamask and jaxx and ether.cards and ledger to decrypt ethereum keys. We didn't make up new paths or re-invent the wheel. We just did what as necessary to unlock the same addresses that users were already using on these other products and services.

 I'm curious to know which service you generated a wallet with that didn't use this/these paths?

**Comment by mmazi** [comment]
I see, so I guess the missing BIP 44 change level is a Ledger issue; I'll ask them.

I used my own software to create the mnemonic and the keys, based on BitGo's HD wallet implementation.

The original issue stands though: I'd still like to be able to select BIP 44 accounts and not be constrained to the 0 account only. (E.g. Ledger's Bitcoin Chrome wallet supports BIP 44 accounts.)

**Comment by tayvano** [comment]
So we may add support for this in the future if it's requested more often, but we feel like it's a pretty rare use-case. However, you can manually change the path (confirmed using chrome) in the following way. 

1. Go to send tab or whatever tab you want to interact with.

2. Click mnemonic and then right click **on the text area** and select "inspect".

3. Click on the console tab in developer tools.

4. Copy and paste the following (changing the account to whatever you want)

**24 word key**
`angular.element($0).scope().$parent.HDWallet.ledgerPath = "m/44'/60'/1'/0"`

**12 word key**
`angular.element($0).scope().$parent.HDWallet.jmPath = "m/44'/60'/1'/0"`

5. Hit enter.

6. Enter your mnemonic in the textarea and hit enter

7. It will display the addresses associated with this account.

The most annoying thing is that you will have to do this before unlocking the wallet each time  as the variable gets reset each time you refresh or switch pages on MEW. 

I totally understand that this isn't the most viable solution for people accessing wallets on a consistent basis but we simply have so much on our plate right now that we have to prioritize. 

---

I think the ideal solution for this would be a small link *above* the mnemonic text area that says "Set Path Manually". When clicked it would display an input with `m/44'/60'/0'/0` set as default. 

["Paste/Type Your Mnemonic"]
[small text link that no one except ppl who wanted it would notice] / [input w/ path]
[textarea for mnemonic]

User could change it, then enter mnemonic, and unlock the wallet and it would use that path. Would need front end validation to verify it's a valid path. Then it would simply be a change to use the ng-model of that field instead of the other paths [here](https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/controllers/decryptWalletCtrl.js#L106). Obviously if the user never clicked the button, the field would remain with the default, and that would be used. 

Other option would be a localstorage value that you could set and change and https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/controllers/decryptWalletCtrl.js would check for a value in local storage before using the default paths. 

Anyone who wants this feature is free to open a PR or we'll get to it when we're bored one day  😛

**Comment by mmazi** [comment]
Thanks for the in-depth reply. I'll test it with Ledger Nano (the above answer is for the mnemonic). If it works, it will be fine for my use case.

> I think the ideal solution for this would be a small link above the mnemonic text area 

Please note that this should also work for other radio-button options (eg. Ledger Nan S), not only for the mnemonic variant. But yeah, this sounds like a flexible and not-too-hard-to-implement solution.

**Comment by mmazi** [comment]
I've filed an issue with Ledger regarding their use of m/44'/60'/0' as the parent to derive addresses from:
https://github.com/LedgerHQ/ledger-wallet-ethereum-chrome/issues/7

**Comment by tayvano** [comment]
The ledger radio uses `$scope.HDWallet.ledgerPath` as well so it should work. It may not though as there are some extra items around the Ledger obviously. Let me know.

**Comment by jase1981** [comment]
Relevant pull request: #326

**Comment by tayvano** [comment]
This is live as of v3.4.7
