### ISSUE TITLE
Can't interact with contract using Ledger Nano S

### ISSUE THREAD

**Issue by nvtaveras** [kvhnuke/etherwallet#329]
Whenever I try to write to a contract from the "Contracts" section (after entering the address + abi), and select my ledger device, the modal doesn't show the accounts under my ledger device (the background turns grey, but the modal doesn't pop up). 

I can see under the network tab that the accounts are fetched with the correct balances, however they won't show up in the UI. No errors received on the developers console.

I can see my accounts without problems when using the Send Ether & Tokens section, so looks like is only a problem with contracts.

Note: This was tested using the current version available on https://www.myetherwallet.com/

**Comment by tayvano** [comment]
@kvhnuke 

This needs to be fixed too.

When the user clicks the "write" button, the <wallet-decrypt-drtv></wallet-decrypt-drtv> should appear below that button, NOT in a modal. It should be the same <wallet-decrypt-drtv> that we use in deploy, as there is no sense in it having all that code twice.

Then you have 2 bindings for messages below that.

Then you have 2 (NOT 4!) ares for the raw and signed transaction.

Then you have the button for each deploy & interact that opens the SINGLE modal to confirm & send. Because they're freaking identical modals except for a single line of copy. 

We just have 2x the code.

We can't put the decrypt in a modal anymore because of the Ledger stuff. I'm going to have to check and see where else that is happening. 

Fuck modals. Never again.

**Comment by tayvano** [comment]
Pushing live shortly. v 3.4.7
