### ISSUE TITLE
Error message of [Object object] when sending from Ledger Nano S while MEW is also viewing Trezor wallet info in another browser

### ISSUE THREAD

**Issue by michaelriha** [kvhnuke/etherwallet#336]
I was trying to move all of my ETH from my Ledger Nano S (purchased because Trezor hadn't added support yet) to my Trezor. I opened the Trezor wallet from Firefox and the Nano S from chrome. When I clicked "Send Transaction" I get an error [Object object]. I'm guessing it should say "You can't connect two devices at the same time" or similar. I got an error on the Trezor screen "Another U2F device was used to register on this application". 

In the screenshot, the Nano S is on the left and Trezor is on the right. 
![screenshot 2017-02-09 12 06 03](https://cloud.githubusercontent.com/assets/1487428/22801312/3566e496-eec1-11e6-953a-638cc274c334.png)

**Comment by tayvano** [comment]
I will look into this and see if we can detect / show better error message. Can you confirm if your Trezor works in Firefox when you don't have 2 devices connected?

**Comment by michaelriha** [comment]
Yes both devices work when only one is connected at a time. 

This is probably reproducible regardless of the browser e.g. you could open a second private browsing window in Chrome so that MEW sees two sessions. Firefox is my main browser, but the Nano S doesn't support it so that's why I used both. 

Also if it's relevant I think I had Firefox open viewing the Trezor wallet info before I opened Chrome to connect to the Nano S.

**Comment by tayvano** [comment]
Thank you for the add'l info! I knew that Ledger didn't support Firefox but interesting to note that Trezor does. 

We will definitely look into this.

**Comment by JanKalin** [comment]
I don't think it has anything to do with Trezor. I just received Ledger Nano S and was playing with it, when I got the same error. It was the only device plugged into USB ports.

My guess is that there is some sort of timeout occurring during communication with Ledger, perhaps caused by the U2F plugin. I can generate a transaction if I confirm it within 10 seconds. So after I click on `Generate Transaction`:
- If I wait more than 10 seconds, I get the error `[object Object]`
- If I confirm within 10 seconds, the transaction is generated
- If I deny within 10 seconds, I get an error `Invalid status 6985`

Windows 7 64bit, Firefox 51.0.1 (32-bit), https://addons.mozilla.org/en-GB/firefox/addon/u2f-support-add-on/?src=api v1.0.1

**Comment by tayvano** [comment]
@kvhnuke  Need better error messages for this. Returning [object object] -> straight to ALL your inboxes. #motivation?
