### ISSUE TITLE
balance stolen

### ISSUE THREAD

**Issue by roronano** [kvhnuke/etherwallet#396]
hi, 
i login to my ether wallet, and found that all of my balance have been transferred to another address !!!
do u have any idea ???

my wallet: 0x689B5Fc06B92059FAA691350AF18fe6dc7cBa13E
all my balance transferred to 0x8478FEA1DD6B9107393C1aa4DA4fDeeEb88F880b 
which is then transferred to:  0xFa52274DD61E1643d2205169732f29114BC240b3 

Note:
i login to my wallet through:
https://www.myetherwallet.com

what should i do?

Thanks in advance…

BR

Raid Nahi

**Comment by tayvano** [comment]
Hello Raid,

I’m really sorry, but it sounds like you may have been the victim of a phishing attack, malware, remote-access hack (e.g. via Teamviewer), or something similar. I cannot easily tell you how this could have happened without knowing what you have done since the creation of these keys. :(  

Unfortunately, once a transaction is on the blockchain, it's final. We do actively attempt to track down the people behind these sites and do what we can to warn others, like take down the site, or whatever we can given the particular situation. 

In order to prevent this from happening in the future, I would recommend buying a [Ledger Nano S](www.ledgerwallet.com/r/fa4b?path=/products/) or [Trezor](trezor.io/?a=myetherwallet.com) hardware wallet. This helps keep your keys safe and not on your computer, and you can continue to use MyEtherWallet.com. If you do not feel like an hardware wallet is the proper solution for you, you need to do the following:

1. You need to bookmark https://www.myetherwallet.com/  and only access the site via your own bookmark: https://www.myetherwallet.com/ 

2. You can also install the chrome extension: https://chrome.google.com/webstore/detail/myetherwallet-cx/nlbmnnijcnlegkjjpcfjclmcfggfefdm?hl=en 

3. You need to create a new wallet and also back it up (on a USB drive or printed paper). Instructions can be found here & here.

4. You need to move all funds from any addresses you have to your new, secure account as soon as possible.

5. Moving forward, always check the URL in the chrome bar. It should say myetherwallet.com . If you ever need to check your balance, you can do so on https://etherscan.io.

What you can do to help us in our mission to stop thieves:

1. Go back through your history and see what site you accessed and try to determine how you may have accessed it. Send me the URL(s) you accessed, or applications you may have downloaded.

2. Post a comment on all the addresses that your ETH was moved to on etherscan saying that this account robbed you. This will help others know that this person is a thief in the future.

3. If the transactions end up at a place like Kraken or Poloniex, message them and let them know that they just received stolen funds that were originally from your account. They won't do anything or even reply, but hopefully someone is keeping track of something. 

Lastly, your funds ended up on Kraken: https://etherscan.io/address/0x267be1c1d684f78cb4f6a176c4911b741e4ffdc0  

Again, I'm really sorry.

​
