### ISSUE TITLE
unable to send DGD

### ISSUE THREAD

**Issue by joggraham** [kvhnuke/etherwallet#414]
having toruble setting up a trasnsaction where i send DGD to another wallet.

**Comment by tayvano** [comment]
Did you try the instructions found here? https://myetherwallet.groovehq.com/knowledge_base/topics/how-do-i-send-tokens-and-add-custom-tokens

**Comment by joggraham** [comment]
yes, going through that process it tells me I have insufficient amount to send.

**Comment by tayvano** [comment]
This means you do not have enough Ether in your account to cover the cost of gas. Each transaction (including token and contract transactions) require gas and that gas is paid in ETH.

The first long number displayed is the amount required to cover the cost of the transaction in Wei.

Take that number, divide by 1000000000000000000 and that is the amount of ETH you will need to have in your account in order to send the transaction successfully.

**Comment by joggraham** [comment]
I believe that is the issue. thank you.
