### ISSUE TITLE
Add Rinkeby etherscan.io node

### ISSUE THREAD

**Issue by marri5317** [kvhnuke/etherwallet#421]
Please add https://rinkeby.etherscan.io/ to the list of nodes or another node on the Rinkeby testnet

**Comment by tayvano** [comment]
I need the chain ID in order to do this. 

You can see the files that need updating / adding here:

https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/nodes.js

https://github.com/kvhnuke/etherwallet/tree/mercury/app/scripts/nodeHelpers

ENS: https://github.com/kvhnuke/etherwallet/tree/mercury/app/scripts/ensConfigs

Default Tokens: https://github.com/kvhnuke/etherwallet/tree/mercury/app/scripts/tokens

Default Contract ABIs: https://github.com/kvhnuke/etherwallet/tree/mercury/app/scripts/abiDefinitions
