### ISSUE TITLE
ENS addresses not resolving yet

### ISSUE THREAD

**Issue by linagee** [kvhnuke/etherwallet#460]
![image](https://cloud.githubusercontent.com/assets/636551/25859671/7ab0cb68-349c-11e7-8212-7fa3110dfe4a.png)

It looks like ENS resolution isn't working yet with MEW? (I've tried other combinations, without the .eth, and other names. Everything kept the box red. If I hit submit anyway, it says "Invalid address." at the bottom.)

**Comment by tayvano** [comment]
dude its been FIVE HOURS since people could possibly own domains. 

Priorities:

1. Help everyone who **needs** to reveal in the next 24 hours reveal

2. Help everyone who can't seem to finalize

3. Sleep

4. Make sure clients don't fire taylor or else taylor won't have any money and cant keep running MEW

5. Test this functionality and push live 

😂

**Comment by tayvano** [comment]
@linagee This is working on the send tx page now (type in mewtopia.eth) and I will expand to all address fields when I get a chance. 

Resolution instructions via contract tab are up there as well. If you are already the owner of a name, when you unlock it'll give you the instructions on how to set up with the public resolver. 

We will be adding more interfaces / buttons as time goes on. 

😃
