### ISSUE TITLE
Generic ERC20 token support

### ISSUE THREAD

**Issue by nmushegian** [kvhnuke/etherwallet#49]
Any timeline on adding custom tokens? 
https://github.com/ethereum/EIPs/issues/20

**Comment by tayvano** [comment]
Sorry - didn't realize I had never commented on this. We would absolutely LOVE to have generic interfaces for tokens. I can't promise timeline or anything but know that it is on our todo list and will most likely be the next big featured pushed. Just a matter of finding the time at this point.

**Comment by jgeewax** [comment]
Seems this is making progress? With the "Send tokens" option looks like it works, but I'm getting errors about `Cannot read property 'getData' of undefined` when trying to create a transaction for a custom token. Not sure if this is a bug on my end or not though.

**Comment by tayvano** [comment]
Turns out, if you add a bad token, itll give you errors. Sounds like what is happening here?

To clean out your other tokens: 

Chrome:
1. Open the send token page
2. right click and say inspect element
3. find the console tab
4. scroll all the way down
5. and copy and paste the following and then hit enter
6. `localStorage.clear();`

## 

Safari Instructs:
1. If you don’t see the Develop menu in the menu bar, choose Safari > Preferences, click Advanced, then select “Show Develop menu in menu bar.”
2. Then, in the menu bar, click DEVELOP -> SHOW ERROR CONSOLE
3. Then paste    localStorage.clear();     into the thing that pops up, right next to the blue arrow at the very bottom and press enter.
4. When you refresh your page it should be working again
