### ISSUE TITLE
Generate transaction blocked until block 3798640 for BAT ICO?

### ISSUE THREAD

**Issue by mrbrdo** [kvhnuke/etherwallet#523]
It seemed to me it didn't want to generate the transaction until that block, was that implemented or just some kind of a glitch on my side?

Since I see you did some specific commits regarding the BAT ICO.

**Comment by tayvano** [comment]
What do you mean by "not generated"

Did you send a TX or were oyu not able to sign a tx?

**Comment by sullof** [comment]
I have a similar issue. I sent some BATs from Liqui to my account in MyEtherWallet but the wallet doesn't show the BATs.

**Comment by tayvano** [comment]
@mrbrdo We don't ever block any transactions ever. We only manually set the gas limit for that address in order to prevent OUT OF GAS errors. 

Check your balance on ethplorer.io. Check what node you are on on MyEtherWallet. BAT is a default token and shows in the sidebar without issue for us. Let me know if you are still having issues.
