### ISSUE TITLE
8 decimals and 21,000,000 supply - is 0.21 expected?

### ISSUE THREAD

**Issue by stefek99** [kvhnuke/etherwallet#538]
Sorry for large screenshots, too lazy to do: https://apple.stackexchange.com/questions/105185/how-can-i-stop-my-retina-display-from-taking-2x-sized-screenshots

# So I've created my custom token: https://www.ethereum.org/token

![image](https://cloud.githubusercontent.com/assets/249703/26761309/82b69e40-4924-11e7-9394-49135fad6e6d.png)

# There were 21m, sent 2m, now there is 19m:
![image](https://cloud.githubusercontent.com/assets/249703/26761329/d8c7e474-4924-11e7-91ce-44343b663dab.png)

# In the UI it is displayed as 0.19:
![image](https://cloud.githubusercontent.com/assets/249703/26761332/e2fb54e4-4924-11e7-939e-fc2fae455104.png)

# When I re-add there is some silly validation

![image](https://cloud.githubusercontent.com/assets/249703/26761368/7442b73a-4925-11e7-9c4b-f11166fec0de.png)

Border around the fields suggests there is something wrong?

**Comment by stefek99** [comment]
When I see transaction history in Ethereum Wallet:
![image](https://cloud.githubusercontent.com/assets/249703/26761952/cd9b2d8e-4930-11e7-9098-5b9eca5612a4.png)

It seems like 21,000,000 and 8 decimal places creates `0.21`

And transferring 2,000,000 moves `0.02`

**Comment by tayvano** [comment]
The decimals decide where to be the decimal place. If you look up the account on ethplorer, there should be a decimal field. I would guess that if you didn't explicitily set the decimals, it is either `0` or `18`

**Comment by stefek99** [comment]
I understand decimals as "resolution".

Say there is 21m supply

## My understanding

0 decimals make it `21,000,000`
1 decimal make it `21,000,000.0`
2 decimals make it `21,000,000.00`
3 decimals make it `21,000,000.000`
4 decimals make it `21,000,000.0000`
5 decimals make it `21,000,000.00000`
6 decimals make it `21,000,000.000000`
7 decimals make it `21,000,000.0000000`
8 decimals make it `21,000,000.00000000`

## Alternative understanding
0 decimals make it `21000000`
1 decimal make it `2100000.0`
2 decimals make it `210000.00`
3 decimals make it `21000.000`
4 decimals make it `2100.0000`
5 decimals make it `210.00000`
6 decimals make it `21.000000`
7 decimals make it `2.1000000`
8 decimals make it `0.21000000`

When I run Ethereum Wallet I can view the deployed contract and I have some admin panel, allowing to transfer tokens etc...

![image](https://cloud.githubusercontent.com/assets/249703/26761309/82b69e40-4924-11e7-9394-49135fad6e6d.png)

I'll try to create some dummy tokens on the testnet - thank you #537 - and try to reproduce

https://ethereum.org/token
> decimals = decimalUnits;                            // Amount of decimals for display purposes

---

Note also silly validation, read border on the fields.

**Comment by tayvano** [comment]
@stefek99 

Are you still getting the validation issue. I re-created it once on accident but can't now :( :(

---

Decimals are how divisible something is. 0 decimals = you can only send 1, 2, 3 tokens - not 1.1, .66, etc. 

Since when you send things there are no decimals its more like this

0 Decimals
21000000

8 Decimals
2100000000000000

Ethereum is 18 (WEI is the smallest unit). So if you have a decimal of 18, it's essentially matching ETH so a lot of people choose that. Alternatively you can do 0 (Unicorns / Beercoin) so you can't split them. 

You can see decimals here: https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/tokens/ethTokens.json

You can see WEI to ETH ratio and everything in between here: https://www.myetherwallet.com/helpers.html

---

I'm closing this as I'm trying re-org the issues and redo a todo list with priorities, but feel free to comment or ping me on slack in #general. 👍

**Comment by stefek99** [comment]
# About validation:

![validation](https://user-images.githubusercontent.com/249703/27260025-24cb5802-5419-11e7-9296-481acf04bdf0.gif)

_(hope the animated GIF will play)_

# About decimal places
Thank you for explanation.

Looking at the code: https://www.ethereum.org/token
```
    /* Initializes contract with initial supply tokens to the creator of the contract */
    function MyToken(
        uint256 initialSupply
        ) {
        balanceOf[msg.sender] = initialSupply;              // Give the creator all initial tokens
    }
```
That's where language knowledge kicks in - http://solidity.readthedocs.io/en/develop/types.html - `uint256` has 256 bits, so unlike JavaScript can store `2100000000000000`
