### ISSUE TITLE
Swap : Order Cancelled

### ISSUE THREAD

**Issue by lamtruong1609** [kvhnuke/etherwallet#544]
Amount to send: 
0.9999 eth
Amount to receive: 
0.085533  BTC
Payment Address: 
17igyGiqNgY7HUk8CYhb75HmLZ89ee8mJb
txHash: https://etherscan.io/tx/0x00a5b6a59276f3756094e202e407d99c9a6207c0d665f5ae6f3151d9861f9d6f
REF ID#: Sorry , i forgot to screenshot :(

Why did my order cancel ?
And i did not receive any BTC , then i contacted support by mail.
And now , my problem's not solved. :-1: 
May I receive refund in ETH ? It's so troubling . . . 
Please answer to me soon :(

**Comment by lamtruong1609** [comment]
@tayvano Would you help me ? please :(

**Comment by tayvano** [comment]
Each and every time I will say the exact same thing:

Please go back to https://www.myetherwallet.com/#swap and click the "Issue with your Swap? Contact support." link at the bottom of the page. 

This will send an email to both us and support@bity.com with the information we need from you in order to look into the issue. Namely:
REF ID#: 
Amount to send: 
Amount to receive: 
Payment Address: 

Thanks.

**Comment by lamtruong1609** [comment]
I had sent what you say for more 2 days ?

**Comment by tayvano** [comment]
If you sent then it will be resolved as soon as we can. We are doing the best we can. In the future I advise that you (1) make sure you send the exact amount and (2) make sure you send with high enough fees so that it gets on the blockchain quickly enough. Those are the top two reasons your order wasn't automatically processed. 

![screen shot 2017-06-05 at 4 38 59 pm](https://cloud.githubusercontent.com/assets/7924827/26807798/81f094ea-4a0d-11e7-8388-8ecfe7c3235d.jpg)

**Comment by lamtruong1609** [comment]
Maybe i did not send enough fees , sorry :( it was my first time .
I hope my problem will be solved soon. I really need that ETH now. :(
Thank you , sorry for my impatience.
