### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by kaprikor** [kvhnuke/etherwallet#550]
I sent the ETH to the address. But nothing happened. The transfer was lost, the ETH did not come http://prntscr.com/fgszlf http://prntscr.com/fgtphj

**Comment by tayvano** [comment]
Do you have the private key for the 0x6988 address?

**Comment by pila656345** [comment]
Hello I made myetherwallet 2 months ago and 2 times used!!! I am not sure maybe I created 2 wallets because I have saved all informations on my mac(I see now and there are 2 addresses and 1 privatekey. 
before when I have putted my privat key I saw one wallet adress but now I see diferrent wallet adress
I have sent etheriums on my old wallet address and what I have to do?thanks

**Comment by pila656345** [comment]
how is it possible use one private key wich could open 2 addresses?

**Comment by pila656345** [comment]
I have sent 17 etheriums

**Comment by pila656345** [comment]
help me with this problem

**Comment by tayvano** [comment]
@pila656345 

> how is it possible use one private key wich could open 2 addresses?

1. You mistyped your private key

2. You are using a different private key today than you were 2 months ago

3. You are entering the private key information in a different location

In order to regain access to your account, you need to do exactly what you did the time you opened your account. Were you using the keystore file? Handtyping? Scanning a QR code? Do that again.

I also strongly recommend you do a full search for your computer for files named `UTC--`. These are the keystore files and it may be that you have another one laying around. 

The last characters of the file name is your address, without the prefixing `0x`

So for example you could search for `7cb57b5a97eabe94205c07890be4c1ad31e486a8` in addition to `UTC` to see if you find anything that way.

Lastly, look around for files that are created around the same date you created the wallet. Did you take a screenshot? Save a different format as your key? Save your information in a word doc? Password manager?

**Comment by pila656345** [comment]
please listen me. I always use one private key(I know this exactly) and this key have opened wallet adress where I sent etheriums few days ago.i found on my post letters when I bought etheriums and with wallet address(old). I am sure it is mystake. how could I bought and sent etheriums with old wallet address and use same private key?

**Comment by pila656345** [comment]
in my word document I have 2 wallets address and one key but this key now open another addres

**Comment by pila656345** [comment]
all this information I have saved when created wallet

**Comment by tayvano** [comment]
@pila656345 If you want me to assist, please email me at support@myetherwallet.com and we can talk privately and see what we can do and if there is a way to resolve. We have a couple new scripts I could try to run to eliminate the mistyping issue. 

I cannot help you via github though because the last time I did it resulted in someone posting their private key publicly and then you can ensure someone will find your ETH but it's doubtful they will give it back.

**Comment by tayvano** [comment]
There is a new tool at the very bottom that could prove useful for anyone who hand-typed or wrote their private key: https://www.myetherwallet.com/helpers.html

Enter the address you sent to and the private key you saved and see if it can find it
