### ISSUE TITLE
Bity Transaction 

### ISSUE THREAD

**Issue by mike1968mi** [kvhnuke/etherwallet#571]
I sent .510 ETH from Myetherwallet to 0x1e4ace701f5900c3d57dd50525aabc462137f4ba at Bity,  
reference number BITYL7UNRR , 
I should have received 0.05517497 BTC to 1LtDXqv1JxFM3dVNTidhaoNcWDJQWNo8uc. 

https://etherscan.io/block/3853208

https://etherscan.io/address/0x1e4ace701f5900c3d57dd50525aabc462137f4ba

**Comment by tayvano** [comment]
Please go back to https://www.myetherwallet.com/#swap and click the "Issue with your Swap? Contact support." link at the bottom of the page. 

This will send an email to both us and support@bity.com with the information we need from you in order to look into the issue. Namely:

REF ID#: 

Amount to send: 

Amount to receive: 

Payment Address: 

Thanks.
