### ISSUE TITLE
Tx nonce overlap when starting a new auction while the previous one's transactions are not yet mined

### ISSUE THREAD

**Issue by veox** [kvhnuke/etherwallet#589]
I've went through the ENS page and started two auctions, about 5 minutes apart.

The transactions for the first one have not yet been mined when the second one's have been submitted to the network.

This resulted in nonce overlap, as below:

txhash                                                             | nonce | call     | namehash
:---                                                               | :---: | :---     | :---
0xa77f8ae009b8ea3bf5f1cf54238e9d97746e91b006dbf45821ceee43fede11bd | 6 | startAuction | 0x8f79..
0x30817f669a5142126afcf566bbb57881f3cb17d32c4e89878aaf2438c904b43d | 7 | newBid       | 0x8f79..
0x3c8dd3cc5dbd10287aa39a6d6fe48cd552d8438dddad2aaeee7da184fd016cda | 7 | startAuction | 0x273e..
0x0f2a4e91499f37a3864c22421a56c3c48c438b9c2a6ffa434cb53c044fcc48b0 | 8 | newBid       | 0x273e..

(See [sending account on EtherScan](https://etherscan.io/address/0xa0357a51e63d4d33b2b64c3905c33ac0b82333b7) for an overview.)

This will result in either the bid for `0x8f79..` not being placed, or the auction for `0x273e..` not being started.

There has been a rise of reports (in the ENS gitter channel) that people seem to be missing transactions like this. They are surfacing now, since the auctions have been started about 3 days ago, during a certain large crowdsale, when the txpool was jammed. Due to that, a situation like described could have happened even if their auctions were spaced hours apart.

-----

With MEW's current use pattern, it should be safe to combine the two calls into one `startAuctionsAndBid`. At worst, nonce overlap would then mean that an auction wouldn't have been started.

(Is there a reason why it's done in separate transactions ATM?..)

-----

EDIT: The txs have been mined, and the `startAuction` for `0x273e..` is missing. I'll go ahead an do that from a different account.

**Comment by tayvano** [comment]
@kvhnuke !!!!!

**Comment by kvhnuke** [comment]
Afaik this is more of a server side config than mew code, since it will happen when you provide a gas price less than 20gwei, geth will not increase the nonce as it'll goto the unprocessed tx pool. I bet there is a setting in geth to reduce the min gas price for processing. My last commit actually combined the two txs in to one

**Comment by tayvano** [comment]
@veox 

v3.9.1 combines start + bid which will help

~~attempting to lower geth default price now~~ apparently this was fixed during the recent geth updates soooooooooooooooo....

**Comment by tayvano** [comment]
I send like 10 tx with 1 gwei gas and could no longer get it in the pending tx pool. 

I have no idea how / why this would be happening except during times of very high volume where all our tx pools are overfilled and we rebroadcast unmined txs that are no longer in the tx pool. 

@kvhnuke were missing something here...something isn't making it somewhere and pulling the wrong nonce for a reason. According to you and Nick it shouldn't need to be mined, just in the pool. I see no reason why that wouldn't be in the pool during normal times even with really low gas

**Comment by veox** [comment]
JIC, I didn't fiddle with the server that the wallet should connect to. AFAIR, it was the default "ETH (MyEtherWallet)" one, but can't be 100% sure.

-----

OS: Arch Linux 64-bit, pacman sync on 2017-06-12
Browser: Firefox 53.0.3 (with NoScript allowing `myetherwallet.com` and `myetherapi.com`)

**Comment by tayvano** [comment]
@veox

We're talking with the kickass geth guys about this and making adjustments 

Were you using a hardware wallet? One thing I've noticed is that hardware wallet reports of weird txs are more than non hardware wallets. I think it has to do something with the confirmation on the device itself? And that you could click the generate button three or four or however many times, but confirm the first tx on your hardware wallet, which could lead to you sending with different info than you intended. (This applies much less to ENS as it does to regular transactions)

**Comment by veox** [comment]
Wasn't using a hardware wallet in this case. Was "unlocking the wallet" by copy-pasting the private key from a (software) password manager.

(Was testing to get a grasp of UX, and why people keep failing to reveal bids.)

**Comment by tayvano** [comment]
So since I'm obsessive and track tickets there are a few that don't have a bid or even sometimes a start auction that we've been looking into for a few days before you opened this issue. This issue helped a lot bc it had way more info that I had, and eliminates deciphering user error from server error.  So thank you for that. 

The most common one is like revealing on a different name, revealing using the mask bid amount instead of the bid amount, or mixing up 2 different bids. If you haven't seen it already, the /helpers.html page has some tools that lets you try to match a bid to a reveal. If a user can find their bid tx hash and provide me with the list of bid amounts, mask bids, secrets, names of recent bids, I can usually find a match in a few minutes manually. 

However, it's nearly impossible with people who have 500 ens txs in 2 days or when they have multiple accounts. The only saving grace is more auctions today at least dont have multiple bids. The early days we saw a lot of locked up eth that was severely depressing me.

**Comment by veox** [comment]
As @kvhnuke noted, commit 24d5a8979a5129936ba1dc142bc879c90541a1d5 combined the two transactions into one. The is [present in release v3.9.1](https://github.com/kvhnuke/etherwallet/commits/v3.9.1).

Technically, issue OK to close, unless you folk find the underlying cause still relevant. ;)

**Comment by veox** [comment]
Possibly spoke too soon.

Using MEW v3.9.3.1 (and Firefox 54.0).

Connected to the default "ETH (MyEtherWallet)" node.

Another (massive, txpool size > 2600 on my `geth` node) crowdsale event. Reveal period for mentioned auctions has arrived. :)

Observing same issue with three `usealBid` transactions, so not limited to rapid successive ones (as with `startAuction` and `newBid` before v3.9.1).

If you've got logs for the backend node (also `geth`?..), these are the transaction hashes, submitted in given order, spaced about a minute apart, with a "soft" page reload in between:

`0xe6b03d95c7b6d4545da497e94c3f26630cc50993f6d9529fbb7f022f312d9563`
`0xa0f25524c0bb0918c20ad052610ec5e42937039788fbcee332268c86b2436ec7`
`0x0854a46ea7bf2542f018326d48eb22439e4e6e72ad2bcdbefc5d1a9382a76d9d`

All three have nonce 13, same gas (200000), same gas price (4 shannon/Gwei).

-----

Tentative flow description (haven't looked at the code at all):

* MEW submits transaction to backend;
* page is reloaded, wallet is unlocked (using private key);
* MEW requests ~~nonce~~ transaction count from backend;
* backend is overburdened, has restarted, doesn't have the "pending" tx, or doesn't take it into account.

`geth console` gives me `13` (that is, `0` to `12` are present) for `eth.getTransactionCount(MEWADDR)`. It seems to not count transactions in the `txpool` (and, by extent, `eth.pendingTransactions`), even those that the node itself submitted - checked this with a separate account.

So, the "nonce overlap" can be expected in the presence of unconfirmed transactions.

**Comment by tayvano** [comment]
Which is why I have a fat red banner that says `If your TX is not urgent, we recommend NOT SENDING TODAY. Thank you for understanding.`

Everyone is about to be fucked for the next 8 hours. With the amount of traffic were seeing, we have 10 nodes running now. The fact that node 1 has nonce of whatever while node 2 hasn't seen that TX. is the cause of *this* issue now

**Comment by veox** [comment]
> we have 10 nodes running now

Sorry, failed to connect the dots here! Did see the warning, but assumed perfect `txpool` sync between the nodes (which, understandably, can't be guaranteed).

If these DDoS-like events continue, and you're forced to run several nodes continuosly, perhaps list them separately in the drop-down?.. Although this is a whole new can of worms.

I'll shut up now.

**Comment by tayvano** [comment]
lol 

we're adding a cookie that will ensure when you send from node 1 you will send from that node again the next time (for 24hrs at least). this allows the load balancer to work it's magic & prevents nonce issues (i hope)

still doesnt work if that node crashes but worth a shot, right?

@kvhnuke this on the list for tonight or tomorrow?

**Comment by veox** [comment]
AFAIU this issue has been solved long ago, so closing.
