### ISSUE TITLE
suggest specifying exact tx fee to be used

### ISSUE THREAD

**Issue by nerdralph** [kvhnuke/etherwallet#63]
Instead of:
"We use standard rates for all gas + a itty-bitty bit more to ensure it gets mined quickly"
I suggest:
"We will use the mininum gas of 0.00042 ETH + 5% = .000441 ETH to ensure it gets mined quickly"

**Comment by tayvano** [comment]
Question for you: do you want this changed because you think we are being manipulative or because you wanted to know what our gas price is or what the TX cost is?

I'm thinking of going with the following, as it makes it clear than an increase in gas (say, for a contract) will also increase the TX cost.

A standard transaction using 21000 gas will cost 0.000441 ETH. We use a slightly-above- minimum gas price of 0.000000021 ETH to ensure it gets mined quickly. We do not take a transaction fee.

Thoughts?

**Comment by nerdralph** [comment]
@tayvano You're jumping to conclusions if you think I'm suggesting any deceit.  Good science requires precision, which is what I'm suggesting.
Your idea is an improvement.  The ideal would be to dynamically to report the actual tx fee total in eth.  I was able to calculate it by converting the hex to decimal and doing the math, but it would be much more convenient if that was done automatically.

**Comment by tayvano** [comment]
Sorry. It was an honest question. Just wanted to figure out what problem we are trying to solve. 

I'd really like to get estimateGas implemented as well, which would go hand in hand with this. 

I'll see if I can at least get the updated messaging and dynamic tx cost in the next push. No promises but I'll do my best. 

Thank you.

**Comment by tayvano** [comment]
This still isn't perfect yet. Another recommendation via reddit:

> Hi - the statement re. gas usage didn't make sense and I thought it was the wrong war around. Re-reading it now I understand the meaning but think it could be better worded something like: "A standard transaction using 21000 gas will cost you 0.000441 ETH. This is slightly above the minimum gas price of 0.000000021 ETH to ensure your transaction gets mined quickly. We do not take a transaction fee." IMHO.

Update this item with #191 (or rethink / redo the entire thing?)

**Comment by tayvano** [comment]
Estimate Gas is now way way way better so the gas auto-updates based on the address you are sending to, and therefore send total available balance "just works"
