### ISSUE TITLE
include the extra options that show in "Send ETH" also in the "Only ETH/ETC" options

### ISSUE THREAD

**Issue by sabr-p** [kvhnuke/etherwallet#64]
the option "send ETH" includes the " Transfer total available balance" and "advanced:....." options

however they disappear when the "only ETH/ETH" mode is selected. it would be nice to have these available too    :)

extra stuff:
using these steps, 1) select the ETH option, 2) click on the "transfer total", 3) select "only ETH", the total amount = wallet balance - gas - itty bit 
remains in the field box unchanged
is this a useful workaround, or this total would be wrong (because not direct Tx but using a contract or some other detail) ?

**Comment by tayvano** [comment]
This goes hand and hand with https://github.com/kvhnuke/etherwallet/issues/63 as well. 

So I think what we are looking for is 
1. EstimateGas()
2. Dynamically show the TX cost in ETH
3. Update "transfer total" to adjust based on new dynamic amount rather than original static amount.

**Comment by sabr-p** [comment]
yes, both issues complement each other. 
also, the "backend" engine already does the math for the "transfer total", so it appears it's just needed to throw the internal values onto the UI and show them all nice and separated :)

**Comment by tayvano** [comment]
Added messaging to note that only ETH/ETC TXs have a gas of 60000: `Only ETH / ETC TX: 60000 gas (0.00126 ether)`

Still a temporary solution until we really revamp the gas / eth price / estimateGas() functionality.

**Comment by tayvano** [comment]
The gas now automatically updates for Send Only ETC / Send Only ETH. In addition, the "send entire balance" now works with these as well. 

For send only, a teeny tiny bit may be leftover because of limitations with estimateGas. But, it's so close and much better than before. 

![screen shot 2016-09-16 at 12 36 18 am](https://cloud.githubusercontent.com/assets/7924827/18578564/9d4864f2-7ba5-11e6-8496-28e4979a7133.jpg)
