### ISSUE TITLE
Sign message

### ISSUE THREAD

**Issue by iFA88** [kvhnuke/etherwallet#65]
Please expand the website services with message signing. Sadly i can't code that for this source.

**Comment by pipermerriam** [comment]
Just voicing that the ability to sign arbitrary messages would be helpful for anyone who has a devcon2 token needing upgrading.

**Comment by tayvano** [comment]
Research on how others do it:
- https://support.coinbase.com/customer/portal/articles/1526413-how-do-i-sign-a-message-with-a-bitcoin-address-
- http://imgur.com/a/nUmZ0#aZjRyKX
- https://ip.bitcointalk.org/?u=https%3A%2F%2Fi.imgur.com%2FftumD67.png&t=570&c=cGpa0leGXPYigQ
- https://ip.bitcointalk.org/?u=https%3A%2F%2Fi.imgur.com%2FqXbURuy.png&t=570&c=VTeZrjBoLTdLHA
- https://ip.bitcointalk.org/?u=https%3A%2F%2Fi.imgur.com%2FMtDpQjq.png&t=570&c=zV5qsroh1NWHMQ
- https://ip.bitcointalk.org/?u=https%3A%2F%2Fi.imgur.com%2FcNr6wOp.png&t=570&c=WQEFs2KjH1vQUg

User Info: 
- DO include the current date. This ensures the signature can not be reused on a different day.
- DO include the reason and be specific. This ensures the signature can not be resued for a different reason.
- DO include your nickname and where you use it. This ensures the signature can not be reused
- DO NOT use a compromised machine (virus, keylogger, etc.) to create a signature. Signing unlocks your wallets protection the same way spending bitcoin does.
- DO NOT upload your private key somewhere in order to create a signature.
- DO NOT give your private key to someone else in order to create a signature for you.

**Comment by tayvano** [comment]
Input welcome: do you think we should... 

- auto-include date/timestamp
- just include a date field that encourages a user to input a date (even if there is no validation on it) 
- don't bother. just have a message textarea and the user can choose to include whatever they want

**Comment by tayvano** [comment]
Could probably do with some better messaging and cleanup but let me know your thoughts. 

https://www.myetherwallet.com/#sign-message

To be clear: we were going to push this tomorrow or the next day after some cleanup and further research but had some other pushes and didn't feel like hiding everything to push those. We were lazy, this was functioning, let's see what the people have to say. There is a ton of room for improvement no doubt, which is why I'm leaving this issue open for the time being.

**Comment by raineorshine** [comment]
@tayvano Has this feature been moved? I get a blank screen in Chrome when I load the url. Thanks!

**Comment by tayvano** [comment]
@raineorshine 

Sorry - its on View Wallet Details and https://www.myetherwallet.com/signmsg.html

Pushing an update now to fix the minor issue of not having a place to enter your key on https://www.myetherwallet.com/signmsg.html

**Comment by raineorshine** [comment]
@tayvano Thanks!

**Comment by derEremit** [comment]
unfortunately this is missing trezor integration, is that a bug, or not planned?

**Comment by tayvano** [comment]
It's a separate functionality that we have to develop (same with Ledger). Please open a separate issue. I'll see if I can find any docs.
