### ISSUE TITLE
Can decrypt private key with multiple passwords?

### ISSUE THREAD

**Issue by SuperHenkie** [kvhnuke/etherwallet#7]
While trying out Ether Wallet, I accidentally ran into a strange issue. At some point it created this encrypted private key:

`U2FsdGVkX1+1uLo9NeVrIFUlCiMRkAwUMfIzBA54okCUhtUirLz+W3A48c9PR61WhKv2H5GfsEctki+RPoDfqjS5lKQqFazKOqDpULTrkLgVHv5xfP6g+gQB8XvBAdpU`

I used `asdfasfd` as password (actually meant to type 'asdf' twice, but made a typo).

However in the 'Send Transaction' page, when pasting that private key, and entering `asdfasdf` (note: spelled differently, swapped the d and f at the end) it says 'Wallet successfully decrypted' and gives me a different address. 
And accidentally I hit another false positive: decrypting that same private key with `asdfasdfd` (note the extra d at the end) it _again_ says Wallet successfully decrypted' and gives me yet another address. And `asdfasdfda` works too! And I guess there's infinitely more. 

It still does seem to decrypt the key to the correct address when using the correct password, but I'd say it should be **infeasible at best** to enter a wrong password and still decrypt it, right?

**Comment by kvhnuke** [comment]
yea true, currently it'll only decrypt the correct privkey if you enter the correct password. but, i agree there should be better validation. I'll add a hash of the address to the end of the encrypted privkey, that way we can verify the final address is the correct address. Im going to add this as a feature request, since it should be backward compatible for users who generated encrypted privkeys from the old method.

**Comment by kvhnuke** [comment]
added this feature, generated encrypted private keys will now have a checksum based on the hash of the address

**Comment by SuperHenkie** [comment]
:thumbsup:
