### ISSUE TITLE
Adding ECNS to ETC node section

### ISSUE THREAD

**Issue by ghost** [kvhnuke/etherwallet#761]
Kindly requesting to add ECNS to the ETC node section of MyEtherWallet.

It apparently works the same way as ENS, but on ETC.

The address of the smart contracts are:
---
Ethereum Classic Naming Service is now deployed on ETC mainnet!

Hash Registrar address: https://gastracker.io/addr/0x68ed1d83939a4a7d324043d98c53cd31f0d93e84

Registry address: https://gastracker.io/addr/0xb96836a066ef81ea038280c733f833f69c23efde

For more information see ECNS on github: https://github.com/Dexaran/ECNS
---

Source: https://www.reddit.com/r/EthereumClassic/comments/6nvuoa/ecns_bug_bounty_program_is_now_finished_no_bugs/

Tank you!

**Comment by rokurota** [comment]
Taylor, for how much longer are we going to service the ETC community? The community that steals from us, mocks us, embarrasses us? There are 78 other issues. I think this should be bottom priority, despite Donald's desire to see his ETC portfolio grow in value.

**Comment by tayvano** [comment]
@rokurota Until you contribute a single line to this repo or, frankly, *anything* else surrounding MEW, you are in no position to decide what is or is not a priority.

**Comment by rokurota** [comment]
I'm not a developer, but I've been in this space for 2 years. I'm a huge fan of your website, and a donator as well. I donate because you are literally the embodiment of all the great things this community represents. Donald, on the other hand, is an investor/philosopher. And he's using his sway to use up your valuable resources to shill his own book. 

Granted, you are free to spend your development time however you please (as I am free to comment however I please). I just don't like seeing people take advantage of our community any longer. Has Donald contributed a line of code to MEW? No, but he feels the right to ask for special requests. Then so shall I. My special request is to stop servicing a) ETC scammers/pumpers, and b) people who are using your platform to boost their own fucking net worth.

It was one thing to copy your open source code (with Classic Ether Wallet). Fine, I get it. It's open source. It was a bit of a stretch to ask for ETC functionality in MEW as well. Ok, I *guess* in the spirit of promoting a free and tolerant community we can have those scumbags use MEW as well. That's your right to support them as well (even though deep down I know you and everyone else hate their miserable guts). But now servicing their ENS? And then start servicing their tokens, and their ICOs, and god knows what else? All on your dime? Do these people even donate? I donated 2 ETH which was worth $30 at the time. I don't even fucking use MEW (although I recommend it to everyone I know). You're always complaining (rightfully so) how this is a bit of a thankless job (or that you're inundated with stupid requests from selfish people). **Stop servicing the selfish people.**

This is a bridge too fucking far.

**Comment by tayvano** [comment]
Our valuable resources are currently being fucked by scammers, icos, and ppl who like clicking phishing links. 

Since you are overly concerned by our time and resources, I'll comment on your choices too: your time would be better served helping the community. In the time it took to write that argument you could have written any number of posts helping people understand Ethereum or not be phished or quite literally anything. 

It's 4 lines of code that need to be changed. The same amount as adding a token for the millionaire icos, which we are forced to do because otherwise we have literally 1000 emails from *our users*. 4 lines of code is the easiest thing about this product. We don't need money. We need people to start helping this community and build resources for education. Fyi, you don't have to be a dev for that. 

Our time is not consumed coding at the moment. Our time is consumed by people yelling or crying or refusing to read the help center in favor of personal attention. Or, meeting with lawyers or writing checks for trademark filings. 

I would do just about anything to push a new feature that wasn't phsihing or fucking icos. A 4 line feature sounds even better, thank you very much. 

We did not support etc, btw. We needed to support testnet, which also had a chain id, and so including etc was copying 3 files and changing a digit. 

While we appreciate your concern and donation, kindly keep your eth and spend your time yelling helpful advice at people who need it most - the 100k+ ppl who entered Thai space in the last 3 months and don't know what a key is (even tho it's protecting their life savings)

**Comment by rokurota** [comment]
Dude, I *work* in the industry. My *fulltime* job is actually helping educate people *about* Ethereum. I had to make this fake because I was so upset.

In fact, I wouldn't even be upset if Charles or Elaine or whoever the fuck had asked for this request. But a fucking trader/investor? Literally asking for something SOLELY to pad his own fucking trading book? Give me a fucking break. 

"Hey Taylor, can you then please implement a trading software into MEW that gets me onboard every ICO, and then just automate the dumping process on Poloniex. Tank you." Gimme a fucking break.

And to be clear my beef is (obviously) not with you. And I appreciate/admire you standing up for Donald and keeping the civility. That's *why* we donate and *why* you're popular. But someone has to be the "bad guy" and tell Donald to fuck off. I'll gladly take that role.

**Comment by tayvano** [comment]
Then go educate people instead of protecting us; I've officially spent more time reading your shit than it would have taken to write this code.

7m was stolen yesterday. That much has been stolen in the last 15 days. Where's your how to not be phished post? Where is your how to get sites taken down post? Where is your education about private keys and personal security? 

Seriously I'm so sick of people not *doing things to help Ethereum* and instead telling us what to do, not do, or how we're doing it wrong.

**Comment by ghost** [comment]
Hi guys, I am sorry to cause this problem. Just to clarify I proposed to integrate ECNS on MEW because I got some ENS domains on ETH and I want to get them on ETC as well.

I congratulated the ENS team at the time: https://twitter.com/TokenHash/status/885750474766295040

And the MEW team as well: https://twitter.com/TokenHash/status/885913105162682368

I am part of a group that is actively promoting and has brought great awareness to smart contracts and platforms like Ethereum. I tweet about crypto charts and markets because I was a stock broker before so I guess it's in my DNA! My portfolio is very small and I actually have 50% in BTC and 50% in ETH (I do trade ETC and other tokens like ZEC, XRP and LTC, but very little in-n-out trades).

I used MEW several times before, but for minor send/receive/view activities, but recently I used it to get my ENS domains and I found it to be a great product and user experience (I actually learned more about web-to-smart-contract usability due to this experience!) this is why I automatically checked if MEW supported ECNS on it's ETC section.

Another misconception may be that I debate Ethereum security publicly with Vitalik, Vlad, Gun and others a lot, but that is because my interest is for Ethereum to be as secure as possible.

Finally, my project [Etherplan](https://etherplan.com/) will be deployed on Ethereum so this is another reason I need it to be as secure as possible.

Sorry for the verbosity, I hope this serves to clarify the situation!

**Comment by Dexaran** [comment]
@tayvano I can confirm that the ECNS is already deployed on ETC main net. The main ECNS repo is [here](https://github.com/Dexaran/ECNS).

Registry: [0xb96836a066ef81ea038280c733f833f69c23efde](https://gastracker.io/addr/0xb96836a066ef81ea038280c733f833f69c23efde)
HashRegistrar: [0x68ed1d83939a4a7d324043d98c53cd31f0d93e84](https://gastracker.io/addr/0x68ed1d83939a4a7d324043d98c53cd31f0d93e84)

Registry ABI: [ECNS.abi](https://github.com/Dexaran/ECNS/blob/master/abi/ECNS.abi)
Hash Registrar ABI: [HashRegistrar.abi](https://github.com/Dexaran/ECNS/blob/master/abi/HashRegistrar.abi)

Each description of the ENS that you provided to users also applies to ECNS. There is no difference between ECNS and ENS for ordinary users (besides the fact that top level node is `.etc` instead of `.eth`).

If you are suffering from a lack of time, I can place a bounty on a patch for MEW that will enable ECNS. I think that members of the ETC community will participate.

**Comment by sgitt-vassky** [comment]
@tayvano will you add a support for ECNS? Any info?

**Comment by tayvano** [comment]
We will do what we can, when we can. As I have stated a number of times: anyone is free to make a PR. We are exceptionally busy with the phishers and yesterday multisig situation.

**Comment by realcodywburns** [comment]
Modular ENS PR submitted. allows support of ETC, RSK, and whatever else may come. 
need resolver and reverse addresses for `./ensConfigs/ETCConfig.json` 

Testing:
- [x] tld changes with node 
- [x] denomination matches nodes
- [x] lookup auction status
- [x] testnets link to correct tld

- [x] able to start auction
- [ ] reveal bid
- [ ] Finalize bid

**Comment by ghost** [comment]
@tayvano @realcodywburns  @Dexaran @kvhnuke Any updates on here?
