### ISSUE TITLE
I have lost my UTC file

### ISSUE THREAD

**Issue by mucoo52** [kvhnuke/etherwallet#793]
Good evening,

My hard drive has broken and on the hard drive was the utc file.
Is there an alternative way to access my wallet?

kind regards

**Comment by tayvano** [comment]
Did you save the private key or paper wallet backup?

**Comment by mucoo52** [comment]
no unhappily only the utc file

**Comment by tayvano** [comment]
In order to ensure your security & privacy, no sensitive data is ever saved, stored, or transmitted when you use MyEtherWallet. We only have access to the information that is publicly available on the blockchain.

Unfortunately, this means we cannot:
- Recover your private key
- Access you account
- Recover or reset your password
- Reverse or cancel transactions
- Recover your account
- Send your ETH or Tokens from one address to another

There may be a chance that you saved it without realizing it. We recommend:
- Do a full search of your computer, backups, other computers for “UTC--“ and see if the private key shows up. 
- Do a full search of your computer, backups, other computers for your address without the 0x at the beginning.
- If you know when you created it, look through all files during that time period for any text documents.
- Generate a new wallet via https://www.myetherwallet.com/#generate-wallet and take a look and the different options you may have downloaded or saved. Sometimes that helps as it can jog your memory.

In the future, we highly recommend you print out a paper version of your wallet and keep it in multiple physical locations. [You can read more about how to safely back up your wallet here.](myetherwallet.groovehq.com/knowledge_base/topics/how-do-i-save-slash-backup-my-wallet)

Hope this helps out. Let us know if anything wasn't clear or if you need additional assistance.

**Comment by gamalielhere** [comment]
Closing this issue. Don't hesitate to reopen if needed.
