### ISSUE TITLE
add usd/eur values

### ISSUE THREAD

**Issue by kvhnuke** [kvhnuke/etherwallet#8]
add approximate usd/euro value  next to balance and transaction amount

**Comment by SuperHenkie** [comment]
Good idea. FYI you can retrieve the current price from Kraken directly through this public API call:

`https://api.kraken.com/0/public/Ticker?pair=XETHZEUR`

It returns a piece of json, of which `result`→`XETHZEUR`→`c`→[0] contains the last closing price.

Change the last 3 characters EUR into USD for price in $ instead of €.

**Comment by kvhnuke** [comment]
awesome you saved me lot of time, I was checking cryptsy api but they dont have https. I can definitely use your solution thanks.

**Comment by SuperHenkie** [comment]
:thumbsup:
I guess there's more sources you can use, to dampen the influence of temporary spikes at one particular exchange. 

For example, you can get the ETH⇆BTC price through 
`https://shapeshift.io/rate/eth_btc`
or 
`https://poloniex.com/public?command=returnTicker` (the latter returns a whole list currency pairs, you'd need the `BTC_ETH`→`last` part). 

And then get the BTC⇆EUR and BTC⇆USD conversion separately, from e.g
`https://api.bitcoinaverage.com/ticker/global/EUR/`→`last` (and `/USD/`) 
or 
`https://api.coindesk.com/v1/bpi/currentprice/eur.json`→`bpi`→`EUR`→`rate` (and `/usd.json`)

But it's not that urgent, even just using Kraken's price indicator is already a great addition.

**Comment by kvhnuke** [comment]
this is supported now, I'll try to get tayvano to beautify it little bit :)
